### ISSUE TITLE
internal error, uncaught exception "No ELF magic number" 

### ISSUE THREAD

**Issue by nilsbecker** [lpw25/prof_alloc#27]
i run my executable with spacetime which generates a profile. then calling prof_spacetime fails:
```
prof_spacetime process -e ~/.opam/411space/bin/annihil spacetime-89938
Processing series...prof-spacetime: internal error, uncaught exception:
                Owee_buf.Invalid_format("No ELF magic number")
```

this is on 4.11.1+spactime.

**Comment by nilsbecker** [comment]
(i have installed prof_spacetime on the +spacetime switch -- is that a problem?)
[edit:] no, the same happens when i call prof_spacetime from a regular switch. also, this is on macos.

**Comment by lpw25** [comment]
The `-e` option is only supported on platforms using ELF. I think that macos uses mach-o rather than ELF, so that would explain your issue.

The `-e` option is only used for fetching symbol names for C functions. Spacetime is still pretty usable without it.

Installing prof_spacetime on the +spacetime switch will work but probably runs much slower.

These days I would recommend using memtrace instead of spacetime: https://blog.janestreet.com/finding-memory-leaks-with-memtrace/

**Comment by lpw25** [comment]
I'm going to close this issue, since there is no actual bug. It could probably use a better error message or documentation, but I'm very unlikely to make fixes to spacetime at this point. It is basically deprecated in favour of memtrace and memtrace_viewer.

**Comment by nilsbecker** [comment]
ah, ok, my bad. i just copied-and-pasted the example and assumed that the -e option was mandatory. i have tried memtrace before and it was useful, but i wanted to see if i may get additional info from spacetime.

without -e, prof_spacetime does work.
