### ISSUE TITLE
Opam dependencies not correct

### ISSUE THREAD

**Issue by bschommer** [lpw25/prof_alloc#9]
I tried the installation via `opam` and it failed because `conduit` is not available. Installing `conduit` also does not work due to broken dependencies. I believe this is due to the recent changes in `Lwt`.

**Comment by lpw25** [comment]
Could you be more specific about what the issue is, perhaps include an error message in your report? Is the problem that you can't install `conduit` via opam, or is the problem that `prof_spacetime` doesn't specify a dependency on `conduit`?

[According to opam-builder](http://opam.ocamlpro.com/builder/html/report-full.html#conduit) `conduit` should install fine with 4.04. As for the dependency, we probably should specify a dependency since there is a call to the `Conduit` module, but `conduit` is a dependency of `cohttp` so I'm surprised this causes problems.

**Comment by bschommer** [comment]
I think the problem is somewhere else, I tried to reproduce it on another machine and it worked without problem. The original machine I tried it on did not have an external solver and was an old red hat linux.

**Comment by lpw25** [comment]
Fair enough. Opam does all sorts of crazy things when it doesn't have an external solver. I've made #10 to track the fact that we probably should add an explicit dependency on `conduit` even though we already depend on it transitively, just to be on the safe side.
